name: release-helm
on:
  release:
    types: [released] # don't trigger on pre-releases
  workflow_dispatch: # allow manual trigger


permissions:
  contents: read

jobs:
  publish-chart:
    permissions:
      contents: write  # to push helm charts
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@629c2de402a417ea7690ca6ce3f33229e27606a5 # v2
    - uses: stefanprodan/helm-gh-pages@a5c92527816f345553e78c3136b031c91724ecf1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        charts_dir: charts
        target_dir: charts
        linting: off